### PR TITLE
Pre-Install git, Update VSTS-Agent to new version 2.142.1  

### PR DESCRIPTION
**Pull request by megel**
- added installation of [Git](https://stackoverflow.com/questions/46731433/how-to-download-and-install-git-client-for-window-using-powershell) by using  [Choco](https://chocolatey.org/install)
- Version of VSTS Agent updatet to v2.142.1

I have added these lines of Code to `initbuildagent.ps1`:

```PowerShell
# Install Choco & GIT
Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
choco install -y git
```

### CODE REVIEW

**Comment by freddydk** [comment]
Very cool, but I don't think I am allowed to include software like choco in these templates.
I will instead create a field in the template, where you can specify a finalsetupscript URL - a URL to a script, that gets executed after setup is done.
There you can do whatever.
You can use a URL to a script you have in github.
Would that be ok?

**Comment by megel** [comment]
yes, your are right. A **finalsetupscript** as parameter  is a much better solution.
BTW, the **agentversion** as parameter would also be a good choise.

**Comment by freddydk** [comment]
I have added this:
image
Only in my dev branch - so you can use http://aka.ms/getbuildagent2 to try it out (until I merge in)

**Comment by megel** [comment]
Perfect, I have tested this script works!

_During the Weekend, I tried also to extend the ARM-templates but this doesn't work. I think I need to learn Howto-ARM :)_

**Pull request closed without merging**
